layout_spectrum: 0.1845878
typography_spectrum: 0.3727598
color:
  saturation: 0.3578441
  lightness: 0.1656207
  brandStrength: 0.8028674
  brandColors:
    - '#282827'
    - '#FFFFF3'
    - '#BD9B76'
    - '#FFF19A'
    - '#F17865'
  rhythmicContrast: 0.2202487
name: THE LIVING NATION
